development:
  adapter: async

test:
  adapter: async

production:
  adapter: <%= ENV.fetch("REDIS_URL", nil) ? "redis" : "async" %>
  url: <%= ENV.fetch("REDIS_URL") { ENV["REDISCLOUD_URL"] } if ENV.fetch("REDIS_URL", nil) %>
  channel_prefix: WebPortfolio_production

#redis://localhost:6379/1